### ISSUE TITLE
Wrapper function outdated

### ISSUE THREAD

**Issue by mavillan** [fredRos/pyfigtree#1]
After installing figtree and setting the environment variables accordingly, I have some issues when running the example code in your readme. Here is the problem:
```
In [7]: target_densities = figtree(samples, target_points, weights, bandwidth=bandwidth)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-08aecee341c9> in <module>()
----> 1 target_densities = figtree(samples, target_points, weights, bandwidth=bandwidth)

figtree.pyx in figtree.figtree()

TypeError: figtree() takes at least 5 positional arguments (3 given)
```

It seems that figtree functions interfaces have changed since you wrote your wrapper.

**Comment by fredRos** [comment]
I think your setup got mixed up. Did you also install Morariu's wrapper? It relies on cython, which explains your error message in a `.pyx` file. My wrapper is plain python with ctypes. Try to uninstall the cython wrapper and please try again

**Comment by mavillan** [comment]
@fredRos you are totally right, I'm sorry for the confusion. I have uninstalled the cython wrapper of Morarius and worked fine.

Thanks!
